site_name: Biomechanics UdeA
theme:
  name: material
  language: en
  palette:
    primary: teal
    accent: deep orange

nav:
  - Home: index.md
  - Courses:
      - Biomechanics: biomechanics.md
      - Computational biomechanics: computational biomechanics.md
  - Ressources:
      - Datasets: datasets.md
  - Contact: contacto.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - tables
  - footnotes
  - attr_list
